# Generated by Django 6.0.2 on 2026-04-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionLog',
        ),
    ]
